repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/AndrejOrsula/pre-commit-cargo
    rev: 0.5.0
    hooks:
      - id: cargo-fmt
      - id: cargo-clippy
        args: ["--all-targets", "--all-features", "--", "-Dwarnings"]
      - id: cargo-check
        args: ["--all-targets", "--all-features"]
      - id: cargo-test
        args: ["--all-targets", "--all-features"]
