[package]
name = "company_reporting"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.56", features=["derive"]}
crossterm = "0.29.0"
eyre = "0.6.12"
log = "0.4.29"
ratatui = "0.30.2"
ratatui-textarea = "0.9.2"
rusqlite = "0.38.0"
simple-logging = "2.0.2"
strum = { version = "0.27.2", features = ["strum_macros"] }
strum_macros = "0.27.2"
tempfile = "3.24.0"
